server:
  port: 8081
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  application:
    name: sell
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.199.248
    port: 6379
wechat:
  mpAppId: wxce796590a9f0863a
  mpAppSecret: e6322939783531c9ba49388a1c418a6c
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/fanjia/Downloads/coding-117/doc/h5.p12
  notifyUrl: http://sellfanjia.natapp1.cc/sell/pay/notify
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
projectUrl:
  wechatMpAuthorize: http://sellfanjia.natapp1.cc
  wechatOpenAuthorize: http://sellfanjia.natapp1.cc
  sell: http://sellfanjia.natapp1.cc
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/
mybatis:
  mapper-locations: classpath:mapper/*.xml