server:
  port: 8081
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.118:3306/sell?characterEncoding=utf-8&useSSL=false
  application:
    name: sell
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
wechat:
  #  mpAppId: wx67ae3b18a7510021
  mpAppSecret: 6eb34fce597d236793c3b9d3febe06c2
  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/fanjia/Downloads/coding-117/doc/h5.p12
  notifyUrl: http://sellfanjia.natapp1.cc/sell/pay/notify